// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiwD2R_Q0ho_kQZWqUaVnV3w6tf7RMa2g',
    appId: '1:589047463153:web:91bcc8b982183292cd3d50',
    messagingSenderId: '589047463153',
    projectId: 'dating-app-403e1',
    authDomain: 'dating-app-403e1.firebaseapp.com',
    storageBucket: 'dating-app-403e1.appspot.com',
    measurementId: 'G-MBYBD70ZCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA02F-ocpkjPWTlaTzVPR37ye9cN5Y60E',
    appId: '1:589047463153:android:3149225535292d51cd3d50',
    messagingSenderId: '589047463153',
    projectId: 'dating-app-403e1',
    storageBucket: 'dating-app-403e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwVKbICNwnPeKuIDJ4560bNvgHICQOB7A',
    appId: '1:589047463153:ios:83245ba2045b3ddecd3d50',
    messagingSenderId: '589047463153',
    projectId: 'dating-app-403e1',
    storageBucket: 'dating-app-403e1.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwVKbICNwnPeKuIDJ4560bNvgHICQOB7A',
    appId: '1:589047463153:ios:f6c8284c790ddb37cd3d50',
    messagingSenderId: '589047463153',
    projectId: 'dating-app-403e1',
    storageBucket: 'dating-app-403e1.appspot.com',
    iosBundleId: 'com.example.datingApp.RunnerTests',
  );
}
